# Generated by Django 2.2.10 on 2020-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('detail', models.TextField()),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='profile-images')),
            ],
        ),
    ]
